name: che's c/c++ CD

on:
  # pull_request:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -al
    - name: pwd
      run: |
        pwd
    - name: make
      run: |
        make
    - name: run
      run: |
        ./webserver_fork 8080 &
    - name: dokcerPull
      run: |
        docker pull owasp/zap2docker-weekly
    - name: dockerCompose
      run: |
        docker run -v $(pwd):/zap/wrk/:rw --net=host -t owasp/zap2docker-weekly zap-baseline.py -t http://localhost:8080/index.html -r testreport.html
    - name: cat
      run: |    
        cat testreport.html
              #docker-compose -f .github/actions/container/DAST/docker-compose_1.yml up --build --exit-code-from zap
